version: '3'
services:
  postgres:
    image: postgres:13
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=dvna
      - POSTGRES_DATABASE=dvna
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
  inf8100-tp2:
    image: bgsub/inf8100:latest
    ports:
      - 80:80
    depends_on:
      - postgres